class Error(Exception):
    pass


class DuplicatedErr(Error):
    pass
